[project]
name = "easy-pil"
version = "0.4.0"
description = "A Python library built on top of PIL to easily edit/modify images"
readme = "README.md"
keywords = ["easy-pil", "easy pillow", "Pillow", "image editing"]
authors = [
    { name = "Md Shahriyar Alam", email = "mdshahriyaralam552@gmail.com" },
]
requires-python = ">=3.10"
dependencies = [
    "aiohttp>=3.13.5",
    "pillow>=12.2.0",
    "requests>=2.33.1",
    "typing-extensions>=4.15.0",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Build Tools",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
]

[project.urls]
Homepage = "https://github.com/shahriyardx/easy-pil"
Documentation = "https://easy-pil.readthedocs.io/en/latest/"
